### DISCUSSION TITLE
OpenAPI parameters with `style: form` & `explode: true`

### DISCUSSION THREAD

**Discussion by shivjm** [reduxjs/redux-toolkit#2410] [Q&A]
I have this in my OpenAPI spec:
```yaml
  /store/foos/page:
    get:
      tags:
        - foo-controller
      operationId: getFoos
      parameters:
        - name: params
          in: query
          required: true
          schema:
            type: object
            additionalProperties:
              type: string
          explode: true
          style: form
```
@rtk-query/openapi-codegen generates what looks like the correct code:
```javascript
    getFoos: build.query<GetFoosApiResponse, GetFoosApiArg>({
      query: (queryArg) => ({
        url: `/store/foos/page`,
        params: { params: queryArg.params },
      }),
    }),

/* … */

export type GetFoosApiResponse = /** status 200 OK */ FoosPage;
export type GetFoosApiArg = {
  params: {
    [key: string]: string;
  };
};
```
And I call it like this (with React hooks):
```javascript
const { data } = useGetFoosQuery({ params: { foo: "bar", baz: "quux" } });
```
I’d expect this to make a request with a query string like this:
```
?foo=bar&baz=quux
```
Instead, the query string looks like this, because it uses `URLSearchParams` for serialization and the outer object is not flattened:
```
?params=%5Bobject+Object%5D
```
What’s the right way to handle this? I know I can pass a custom `paramsSerializer`, but that function is only passed the parameters, so it can’t reference the `explode` or `style` values and produce the correct output. (I also see that [those values are the defaults](https://swagger.io/docs/specification/describing-parameters/#query-parameters), which makes me wonder whether this is actually a bug.)
