### ISSUE TITLE
Support DeepObject query parameters in codegen

### ISSUE THREAD

**Issue by mattoni** [reduxjs/redux-toolkit#2573]
I'm attempting to describe query parameters such as `/tasks?page[size]=1&page[number]=1`, which is done according to the OpenAPI spec using `style: deepObject` and `explode: true`.  See: https://swagger.io/docs/specification/serialization/

The codegen 'works' in that there are no errors. I'm able to pass an object in the hook:
`useGetTasksQuery({page: {size: 1, number: 1}})`

However, it turns into this in the URL: `/tasks?page=[object+Object]`.

Here's my open api spec for the parameter:
```
---
name: page
in: query
required: false
description: 'In a list return, the data associated with the page number and size returned.'
explode: true
style: deepObject
schema:
  type: object
  properties: 
    number: 
      type: number 
      description: The page to jump to
    size: 
      type: number 
      description: The number of resources returned per page.
```

Is this supported, and if not is it easily added?

Thanks!
