### ISSUE TITLE
TypeError: array.map is not a function - @rtk-query/codegen-openapi

### ISSUE THREAD

**Issue by 12ukas** [reduxjs/redux-toolkit#3719]
I am trying to generate api slice definitions using my OpenApi 3.0.3 schema through "@rtk-query/codegen-openapi".

For example, I have defined the paths "/users/{id}" and "/documents/{id}" as follows:

1. Users path defintion:
```
/users/{id}:
  put:
    ... users put defintion
  delete:
    ... users delete defintion
  parameters:
    $ref: "../parameters/_default.yaml#/pathId"
```

2. Documents path defintion:
```
/documents/{id}:
  get:
    ... documents get defintion
  delete:
    ... documents delete defintion
  parameters:
    $ref: "../parameters/_default.yaml#/pathId"
```
Since the parameter {id} is used several times, I have swapped out the parameter definition and reference it in the place of the ID parameter.

The definition of the pathId parameter:
```
pathId:
  - name: id
    in: path
    required: true
    description: Record.ID
    schema:
      type: integer
      format: int64
```

However, the following error now appears when generating with the command "npx @rtk-query/codegen-openapi openapi-config.ts":
```
TypeError: array.map is not a function
  at ApiGenerator.resolveArray (...\node_modules\@rtk-query\oazapfts-patched\src\codegen\generate.ts:216:26)
  at generateEndpoint (...\node_modules\@rtk-query\codegen-openapi\src\generate.ts:255:17)
  at ...\node_modules\@rtk-query\codegen-openapi\src\generate.ts:144:15
  at Array.map (<anonymous>)
  at generateApi (...\node_modules\@rtk-query\codegen-openapi\src\generate.ts:143:34)
  at generateEndpoints (...\node_modules\@rtk-query\codegen-openapi\src\index.ts:14:22)
  at run (...\node_modules\@rtk-query\codegen-openapi\src\bin\cli.ts:64:7)
```

I was able to find out that my problem is the reused path parameter "id".
If I remove all path definitions that use the "ID / pathId" parameter and leave one, it works.

**Comment by 12ukas** [comment]
I solved my problem as following:

I entered a "-" before my $ref inside the parameters.
```
/documents/{id}:
  get:
    ... documents get defintion
  delete:
    ... documents delete defintion
  parameters:
    - $ref: "../parameters/_default.yaml#/pathId"
```

Removed the "-" before "name"
```
pathId:
  name: id
  in: path
  required: true
  description: Record.ID
  schema:
    type: integer
    format: int64
```
