### ISSUE TITLE
Add size-limit-action

### ISSUE THREAD

**Issue by EskiMojo14** [reduxjs/redux-toolkit#4078]
would be good to see how different PRs affect final size of package

https://github.com/marketplace/actions/size-limit-action previously used

**Comment by markerikson** [comment]
Part of the issue is that I'm less concerned about total _file_ size, and more about _import_ sizes.

It'd be nice to use something like https://github.com/mweststrate/import-size or https://github.com/privatenumber/pkg-size.dev to show the specific sizes of our main exports.

I did recently figure out how to write a miniature comment bot for a PR, by using `thollander/actions-comment-pull-request`, and having part of the job write some Markdown to disk (in this case, containing a Markdown code block that's just formatted JSON).

https://github.com/replayio/devtools/pull/10064/files#diff-faff1af3d8ff408964a57b2e475f69a6b7c7b71c9978cccc8f471798caac2c88R269-R273

```yaml
      - name: Post coverage summary as a PR comment
        uses: thollander/actions-comment-pull-request@v2
        with:
          filePath: ./coverageSummary.md
          comment_tag: coverage_summary
```

We could use something like this to kit-bash together our own import size diffing if we really wanted to:

- Use one of these tools to generate per-function size reports for both the PR build (and the latest release?)
- Compare the results for each
- Format for size changes?

Could also probably swipe some of the React repo's code for bundle size changes or something too, mostly with the "X%+" formatting
